# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charCreate.ui',
# licensing of 'charCreate.ui' applies.
#
# Created: Sun Nov 25 01:54:10 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 550)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_7.addWidget(self.spinBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_8.addWidget(self.spinBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_9.addWidget(self.spinBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_10.addWidget(self.spinBox_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_11.addWidget(self.spinBox_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Create Character", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Dialog", "Details", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "Character Name", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Race", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("Dialog", "Please Select...", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("Dialog", "Dwarf", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("Dialog", "Elf", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("Dialog", "Halfling", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("Dialog", "Human", None, -1))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("Dialog", "Dragonborn", None, -1))
        self.comboBox.setItemText(6, QtWidgets.QApplication.translate("Dialog", "Gnome", None, -1))
        self.comboBox.setItemText(7, QtWidgets.QApplication.translate("Dialog", "Half-Elf", None, -1))
        self.comboBox.setItemText(8, QtWidgets.QApplication.translate("Dialog", "Half-Orc", None, -1))
        self.comboBox.setItemText(9, QtWidgets.QApplication.translate("Dialog", "Tiefling", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Class", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("Dialog", "Please Select...", None, -1))
        self.comboBox_2.setItemText(1, QtWidgets.QApplication.translate("Dialog", "Barbarian", None, -1))
        self.comboBox_2.setItemText(2, QtWidgets.QApplication.translate("Dialog", "Bard", None, -1))
        self.comboBox_2.setItemText(3, QtWidgets.QApplication.translate("Dialog", "Cleric", None, -1))
        self.comboBox_2.setItemText(4, QtWidgets.QApplication.translate("Dialog", "Druid", None, -1))
        self.comboBox_2.setItemText(5, QtWidgets.QApplication.translate("Dialog", "Fighter", None, -1))
        self.comboBox_2.setItemText(6, QtWidgets.QApplication.translate("Dialog", "Monk", None, -1))
        self.comboBox_2.setItemText(7, QtWidgets.QApplication.translate("Dialog", "Paladin", None, -1))
        self.comboBox_2.setItemText(8, QtWidgets.QApplication.translate("Dialog", "Ranger", None, -1))
        self.comboBox_2.setItemText(9, QtWidgets.QApplication.translate("Dialog", "Sorcerer", None, -1))
        self.comboBox_2.setItemText(10, QtWidgets.QApplication.translate("Dialog", "Warlock", None, -1))
        self.comboBox_2.setItemText(11, QtWidgets.QApplication.translate("Dialog", "Wizard", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Ability Scores", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Strength", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Dexterity", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Constitution", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Intelligence", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "Wisdom", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "Charisma", None, -1))

